### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by Sparticuz** [Sparticuz/constellation-site#11]
http://www.jonathantneal.com/blog/understand-the-favicon/

**Comment by Sparticuz** [comment]
https://github.com/audreyr/favicon-cheat-sheet

**Comment by bradmcnally** [comment]
Is the favicon not working for you? I created an .ico file that is 16x16 + 32x32. I haven't done any of the png stuff yet.

**Comment by Sparticuz** [comment]
just an fyi for the iphone stuff and windows 8 stuff

**Comment by bradmcnally** [comment]
Since we've got the regular + retina favicon, I'm going to close this. I may go back and make touch icons, but I don't know anyone who adds web sites to their homescreen.
