### ISSUE TITLE
Products permalink structure

### ISSUE THREAD

**Issue by bradmcnally** [Sparticuz/constellation-site#15]
This is the current permalink structure:
http://beta.constellationco.com/product/product-category/featured/

Can you change it to:
constellationco.com/products/featured

**Comment by Sparticuz** [comment]
Issue pending @
https://github.com/torounit/custom-post-type-permalinks/issues/16

**Comment by bradmcnally** [comment]
So did he give us a solution with that rewrite thing?

**Comment by Sparticuz** [comment]
I think what I can do is have it say 'category' instead of 'product-category'

**Comment by Sparticuz** [comment]
check it out, this is as fixed as it's going to get.

**Comment by bradmcnally** [comment]
works for me
