### ISSUE TITLE
Products sticky menu

### ISSUE THREAD

**Issue by bradmcnally** [Sparticuz/constellation-site#18]
The left side menu should stick once you scroll past it

**Comment by bradmcnally** [comment]
Also, on mobile, the menu should do this.

Closed:
![image](https://f.cloud.github.com/assets/752756/2352852/8783e5be-a593-11e3-8ce5-c653a625bd4e.png)

Open:
![image](https://f.cloud.github.com/assets/752756/2352854/91b949a2-a593-11e3-8cd2-a06dcd542068.png)

**Comment by bradmcnally** [comment]
I've gotten the sticky menu to work, the collapsable menu for mobile still needs to be worked on

**Comment by Sparticuz** [comment]
submenu done, just add styling, _base.scss around lines 460 under #categories

**Comment by bradmcnally** [comment]
Styling for mobile is done. Styling for 768 should be done but may need some tweaks based on what I did for base.scss
