### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by bradmcnally** [Sparticuz/constellation-site#20]
Here is the design for the contact page, I assume this will be a custom layout that won't be editable in wordpress via a page or something.

![image](https://f.cloud.github.com/assets/752756/1843288/ef7d6b6e-74cd-11e3-9dde-970147561652.png)

**Comment by bradmcnally** [comment]
I've started working on this, you can see my progress

**Comment by bradmcnally** [comment]
This page is done on mobile

**Comment by Sparticuz** [comment]
still need to look into custom checkbox images

**Comment by bradmcnally** [comment]
Yeah, but that can be post launch
