### ISSUE TITLE
Hyphenation

### ISSUE THREAD

**Issue by bradmcnally** [Sparticuz/constellation-site#28]
Is there any way to fix this hyphenation?

![image](https://f.cloud.github.com/assets/752756/2462497/eac5cb22-af81-11e3-998a-c3837d7c3baa.png)

**Comment by Sparticuz** [comment]
http://css-tricks.com/almanac/properties/h/hyphenate/

**Comment by bradmcnally** [comment]
I tried that stuff but didn't see any changes

**Comment by bradmcnally** [comment]
JK, i found that _normalize was overriding it.
