### ISSUE TITLE
Mobile - Products Page - SO slow

### ISSUE THREAD

**Issue by bradmcnally** [Sparticuz/constellation-site#31]
When I scroll the products page on my phone, it stops responding every few seconds. Let me know if you encounter this as well.

**Comment by Sparticuz** [comment]
negative, (there are major minification things to do)

**Comment by bradmcnally** [comment]
Was just talking to a friend who said that it might be an ios thing?

**Comment by bradmcnally** [comment]
Yeah, this isnt laggy on safari on ios, only chrome....
