### ISSUE TITLE
Estimate Request form

### ISSUE THREAD

**Issue by bradmcnally** [Sparticuz/constellation-site#36]
Make sure that the php file is hooked up so it can process the information

**Comment by Sparticuz** [comment]
is this a wp plugin?

**Comment by bradmcnally** [comment]
no, we currently use 

http://www.constellationco.com/wp-content/themes/constellation/process.php

**Comment by bradmcnally** [comment]
I moved process.php over to the new site and removed the old fields. There is still the old html email template that needs to be updated and the thank you page.

**Comment by bradmcnally** [comment]
I can't get the new fields to show up in the email (the date isn't showing up either)

I started working on the thankyou.php, thinking that will be what they are forwarded too after the estimate is sent.

here is the design

![image](https://cloud.githubusercontent.com/assets/752756/2559752/0339a8b6-b78b-11e3-9c69-642422386507.png)
