### ISSUE TITLE
Should we use wordpress for blog comments?

### ISSUE THREAD

**Issue by bradmcnally** [Sparticuz/constellation-site#5]
I'm open to other suggestions. What is good?

**Comment by bradmcnally** [comment]
![image](https://f.cloud.github.com/assets/752756/1160583/370d10b2-1fdb-11e3-8f51-aebcfb127f1b.png)

**Comment by Sparticuz** [comment]
up to you, i am in favor of allowing the 'least' restrictive when it comes to logging in and commenting. disqus & facebook are two popular ones

**Comment by Sparticuz** [comment]
using wordpress
