### ISSUE TITLE
Comment text area

### ISSUE THREAD

**Issue by bradmcnally** [Sparticuz/constellation-site#59]
Comments are looking good, but when you replay, the text area box is getting cut off.

![image](https://cloud.githubusercontent.com/assets/752756/2557363/f2317904-b6fe-11e3-8b94-e3e29ba11f60.png)

**Comment by Sparticuz** [comment]
i think the width of the text box should be 100%?

**Comment by bradmcnally** [comment]
I think that it is set to that, but using margin-left to indent might be pushing it off the side?

**Comment by bradmcnally** [comment]
The issue seems to resolve if I change the width to 90%
