### ISSUE TITLE
Should we use SVG's for these?

### ISSUE THREAD

**Issue by bradmcnally** [Sparticuz/constellation-site#6]
I remember you talking about some encoding thing

![image](https://f.cloud.github.com/assets/752756/1161562/f79f30de-1ff0-11e3-8692-2fa39391b64f.png)

**Comment by Sparticuz** [comment]
Yes, they should be implemented as SVG's in Data URI's. 

See here: http://dataurl.net/#about

Basically, any image that is smaller then 4kb should be encoded into a URI. This will save on the number of HTTP Requests

**Comment by bradmcnally** [comment]
Hmm. The dataurl is larger than the actual file

**Comment by bradmcnally** [comment]
oh

For example, the required base64 encoding for an image 600 bytes long would be 800 bytes, so if an HTTP request required more than 200 bytes of overhead, the data URI would be more efficient

**Comment by bradmcnally** [comment]
Looks like we'll need to implement it another way, it's so smalllllll

**Comment by Sparticuz** [comment]
each individual image should be a seperate dataurl, instead of using sprites basically.

**Comment by Sparticuz** [comment]
this is done
