### ISSUE TITLE
figcaption

### ISSUE THREAD

**Issue by bradmcnally** [Sparticuz/constellation-site#64]
Looks like its not centering on a few pages

![image](https://cloud.githubusercontent.com/assets/752756/2557415/3a2098e2-b701-11e3-9765-e4b56fbed006.png)

![image](https://cloud.githubusercontent.com/assets/752756/2557416/4b5adbcc-b701-11e3-90f7-20fb327a5ae7.png)

**Comment by Sparticuz** [comment]
https://github.com/Sparticuz/constellation-site/blob/master/library/scss/_base.scss#L48

https://github.com/Sparticuz/constellation-site/blob/master/library/scss/_base.scss#L78

**Comment by bradmcnally** [comment]
It seems to be working fine on some pages, but not others. confused.
