### ISSUE TITLE
Nav item on Single

### ISSUE THREAD

**Issue by bradmcnally** [Sparticuz/constellation-site#66]
Can the blog nav item be black when you are on single.php

**Comment by Sparticuz** [comment]
pic?

**Comment by bradmcnally** [comment]
You can see that i'm on the actual single post page. I'd like the blog nav item to look like it's the current item
![image](https://cloud.githubusercontent.com/assets/752756/2559638/01ab0c12-b784-11e3-950e-43723b68a6f0.png)

**Comment by Sparticuz** [comment]
oh, i see, you need to target

```
.current_page_parent
```

on https://github.com/Sparticuz/constellation-site/blob/master/library/scss/_768up.scss#L167
