### ISSUE TITLE
Migrate blog posts

### ISSUE THREAD

**Issue by bradmcnally** [Sparticuz/constellation-site#7]
Migrate blog posts to the new site. Sara and I will go through and remove ones that we don't want to bring over. I will also make sure they fit with the new design.

**Comment by Sparticuz** [comment]
i think we'll make a copy of the db and then upgrade it, then you can remove whatever content you want

**Comment by bradmcnally** [comment]
I ended up choosing the posts i wanted and exporting them from the old site.

They are now all in the beta site.
